import streamlit as st
import pandas as pd
import os
from datetime import datetime

# ==============================================================================
# 1. APP CONFIGURATION & AESTHETICS
# ==============================================================================
st.set_page_config(
    page_title="RavenStack CRO Terminal",
    page_icon="",
    layout="wide",
    initial_sidebar_state="collapsed"
)

CSS_OVERRIDE = """
<style>
    .stApp {
        background-color: #EFF1FF;
        color: #1E293B;
        font-family: 'Inter', 'Segoe UI', sans-serif;
    }
    label, div[data-testid="stWidgetLabel"] p, .stSelectbox label p {
        color: #1E293B !important;
    }
    div[data-baseweb="select"] > div {
        background-color: #FFFFFF !important;
        color: #1E293B !important;
        border: 1px solid #CBD5E1 !important;
        border-radius: 8px !important;
        box-shadow: 0 2px 4px rgba(0,0,0,0.02) !important;
    }
    div[data-testid="metric-container"] {
        background-color: #FFFFFF !important;
        border: 1px solid #E2E8F0 !important;
        border-top: 4px solid #6366F1 !important;
        padding: 20px !important;
        border-radius: 12px !important;
        box-shadow: 0px 8px 24px rgba(149, 157, 165, 0.15) !important;
        transition: transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out;
    }
    div[data-testid="metric-container"]:hover {
        transform: translateY(-3px);
        box-shadow: 0px 12px 32px rgba(149, 157, 165, 0.25) !important;
    }
    div[data-testid="metric-container"] *, div[data-testid="stMetric"] * {
        color: #0F172A !important;
    }
    div[data-testid="stMetricValue"] > div {
        font-weight: 800 !important;
        font-size: 2.2rem !important;
        color: #0F172A !important;
    }
    div[data-testid="stMetricLabel"] *, div[data-testid="stMetricLabel"] p {
        color: #475569 !important;
        font-weight: 700 !important;
        font-size: 1.05rem !important;
    }
    div[data-testid="stMetricDelta"] *, div[data-testid="stMetricDelta"] div, div[data-testid="stMetricDelta"] svg {
        color: #64748B !important;
    }
</style>
"""
st.markdown(CSS_OVERRIDE, unsafe_allow_html=True)


# ==============================================================================
# 2. ROBUST DATA INGESTION
# ==============================================================================
REQUIRED_COLUMNS = [
    'account_id', 'industry', 'active_mrr_run_rate',
    'flight_risk_score', 'primary_risk_drivers', 'tenure_days'
]


@st.cache_data(ttl="1h")
def load_risk_data():
    """
    Safely locate and load the CSV generated by the Jupyter Notebook.
    Handles relative pathing regardless of where Streamlit is executed from.
    Returns (dataframe, file_last_modified_datetime).
    """
    base_dir = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(base_dir, '..', 'data', 'live_flight_risk_scores.csv')

    if not os.path.exists(data_path):
        data_path = 'live_flight_risk_scores.csv'

    try:
        df = pd.read_csv(data_path)
    except FileNotFoundError:
        st.error(f"Critical Error: Could not find '{data_path}'. Please ensure the ML pipeline ran successfully.")
        st.stop()

    # NEW FIX (audit finding): validate schema at the ingestion boundary.
    # If the notebook's output ever drifts, fail here with a clear message
    # instead of a raw KeyError deep inside the render logic below.
    missing_cols = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing_cols:
        st.error(
            f"Critical Error: live_flight_risk_scores.csv is missing expected "
            f"column(s): {missing_cols}. The notebook's output schema may have "
            f"changed. Re-run the pipeline before loading this dashboard."
        )
        st.stop()

    # NEW FIX (audit finding): duplicate account_id would silently mask a
    # data-quality issue in the account deep-dive lookup (iloc[0] would just
    # grab the first match). Surface it instead of hiding it.
    dupe_count = df['account_id'].duplicated().sum()
    if dupe_count > 0:
        st.warning(
            f"Data quality notice: {dupe_count} duplicate account_id row(s) "
            f"detected in the source file. Showing first occurrence per account."
        )
        df = df.drop_duplicates(subset='account_id', keep='first')

    last_modified = datetime.fromtimestamp(os.path.getmtime(data_path))
    return df, last_modified


df, data_last_modified = load_risk_data()


# ==============================================================================
# 3. EXECUTIVE DASHBOARD (KPIs)
# ==============================================================================
st.title("🦅 RavenStack CRO Terminal")
st.markdown("### Revenue Risk & Churn Exposure")

# NEW FIX (audit finding): surface data freshness. This dashboard runs on
# a cached, periodically-regenerated model output — not a live feed — and
# a CRO making revenue decisions needs to know how current the score is.
st.caption(f"Risk scores last computed: {data_last_modified.strftime('%B %d, %Y at %I:%M %p')}")

# NEW FIX (audit finding): make the high-risk threshold adjustable instead
# of a hardcoded 0.60 buried in code — a business-definition choice like
# "what counts as high risk" shouldn't require an engineering change.
risk_threshold = st.slider(
    "High-Risk Threshold (Flight Risk Probability)",
    min_value=0.0, max_value=1.0, value=0.60, step=0.05,
    help="Accounts at or above this predicted risk score are counted as high-risk exposure below."
)

total_mrr = df['active_mrr_run_rate'].sum()
high_risk_df = df[df['flight_risk_score'] >= risk_threshold]
at_risk_mrr = high_risk_df['active_mrr_run_rate'].sum()
avg_risk = df['flight_risk_score'].mean()

pct_at_risk = (at_risk_mrr / total_mrr * 100) if total_mrr > 0 else 0.0

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        label="Total Active MRR",
        value=f"${total_mrr:,.0f}"
    )
with col2:
    st.metric(
        label=f"High-Risk MRR Exposure (\u2265{risk_threshold:.0%} Prob)",
        value=f"${at_risk_mrr:,.0f}",
        delta=f"{pct_at_risk:.1f}% of total portfolio revenue",
        delta_color="off"
    )
with col3:
    st.metric(
        label="Average Portfolio Risk",
        value=f"{avg_risk * 100:.1f}%"
    )

st.markdown("---")

# ==============================================================================
# 4. INTERACTIVE RISK MATRIX
# ==============================================================================
st.markdown("### Global Flight Risk Roster")

column_formatting = {
    "account_id": st.column_config.TextColumn("Account ID", width="medium"),
    "industry": st.column_config.TextColumn("Industry", width="medium"),
    "active_mrr_run_rate": st.column_config.NumberColumn(
        "MRR Run Rate",
        format="$%.2f",
        width="small"
    ),
    "flight_risk_score": st.column_config.ProgressColumn(
        "Flight Risk Probability",
        # FIX (audit finding): removed the incorrect "within 30 days" claim.
        # The model was trained on whether an account EVER churns, using
        # trailing 30-day behavior as input features — it does not forecast
        # a fixed churn timeline. Overstating precision here could mislead
        # decision-making.
        help="Model-predicted likelihood of eventual churn, based on the account's most recent 30 days of behavior.",
        format="%.2f",
        min_value=0.0,
        max_value=1.0,
        width="medium"
    ),
    "primary_risk_drivers": st.column_config.TextColumn(
        "Top SHAP Risk Drivers",
        width="large"
    ),
    "tenure_days": st.column_config.NumberColumn(
        "Tenure (Days)",
        width="small"
    )
}

st.dataframe(
    df,
    use_container_width=True,
    hide_index=True,
    column_config=column_formatting
)

st.markdown("---")

# ==============================================================================
# 5. ACCOUNT DEEP-DIVE
# ==============================================================================
st.markdown("### 🔍 Individual Account Inspection")

selected_account = st.selectbox(
    "Search or Select Account ID to view specific intervention strategies:",
    options=["-- Select Account --"] + list(df['account_id'].unique())
)

if selected_account != "-- Select Account --":
    acc_data = df[df['account_id'] == selected_account].iloc[0]

    st.info(f"**Account {selected_account}** ({acc_data['industry']}) has been active for **{acc_data['tenure_days']} days**.")

    colA, colB = st.columns(2)
    with colA:
        st.warning(f"**Flight Risk Score:** {acc_data['flight_risk_score'] * 100:.1f}%")
        st.success(f"**Monthly Revenue:** ${acc_data['active_mrr_run_rate']:,.2f}")
    with colB:
        st.error(f"**Primary Intervention Triggers:**\n\n{acc_data['primary_risk_drivers']}")